apiVersion: batch/v1
kind: CronJob
metadata:
  name: products-report-job
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: products-report-job
              image: scheduler-jobs:latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure